

let inventory =[
    //---------------------BOARDS ------------------//
    {
        name: "Red Baron",
        description:"skimboard",
        tag: 'boards- red baron',
        brand:"",
        image:'<img src="shop-images/single-boards/board1.png" alt="board-img" id="favb">',
        price: 2400,
        inCart: 0
    },
    {
        name: "Black One",
        description:"skimboard",
        tag: 'boards-black one',
        brand:"",
        image:'<img src="shop-images/single-boards/board2.png" alt="board-img" id="favb">',
        price: 2400,
        inCart: 0
    },
    {
        name: "Blk and Blue",
        description:"skimboard",
        tag: 'boards-black and blue',
        brand:"",
        image:'<img src="shop-images/single-boards/board3.png" alt="board-img" id="favb">',
        price: 2600,
        inCart: 0
    },
    {
        name: "Plane Jane",
        description:"skimboard",
        tag: 'boards-blue',
        brand:"",
        image:'<img src="shop-images/single-boards/board4.png" alt="board-img" id="favb">',
        price: 2100,
        inCart: 0
    },
    {
        name: "Classic Fish M (zebra)",
        description:"skimboard",
        tag: 'boards-classic fish Medium medium (zebra)',
        brand:"",
        image:'<img src="shop-images/boards/board-1.png" alt="board-img">',
        price: 2400,
        inCart: 0
    },
    {
        name: "Classic Fish M (yellow)",
        description:"skimboard",
        tag: 'boards-classic Fish M (yellow)',
        brand:"",
        image:'<img src="shop-images/boards/board-2.png" alt="board-img">',
        price: 2400,
        inCart: 0
    },
    {
        name: "Flying Fish XS",
        description:"skimboard",
        tag: 'boards-flying fish XS Extra-Small extra-small',
        brand:"",
        image:'<img src="shop-images/boards/board-3.png" alt="board-img">',
        price: 1800,
        inCart: 0
    },
    {
        name: "Flying Fish XS",
        description:"skimboard",
        tag: 'boards-flying fish XS Extra-Small extra-small',
        brand:"",
        image:'<img src="shop-images/boards/board-4.png" alt="board-img">',
        price: 1800,
        inCart: 0
    },
    {
        name: "Classic Fish S",
        description:"skimboard",
        tag: 'boards-classic fish Small small',
        brand:"",
        image:'<img src="shop-images/boards/board-5.png" alt="board-img">',
        price: 2000,
        inCart: 0
    },
    {
        name: "Lift Shape MS",
        description:"skimboard",
        tag: 'boards-lift shape MS medium-small Medium-Small',
        brand:"",
        image:'<img src="shop-images/boards/board-6.png" alt="board-img">',
        price: 2100,
        inCart: 0
    },
    {
        name: "Lift Shape ML",
        description:"skimboard",
        tag: 'boards-Lift Shape ML medium-large Medium Large',
        brand:"",
        image:'<img src="shop-images/boards/board-7.png" alt="board-img">',
        price: 2500,
        inCart: 0
    },
    {
        name: "Lift Shape S",
        description:"skimboard",
        tag: 'boards-lift shape Small small',
        image:'<img src="shop-images/boards/board-8.png" alt="board-img">',
        brand:"",
        price: 2000,
        inCart: 0
    },
    {
        name: "Flying Fish M",
        description:"skimboard",
        tag: 'boards-flying fish Medium medium',
        image:'<img src="shop-images/boards/board-9.png" alt="board-img">',
        brand:"",
        price: 2300,
        inCart: 0
    },
    {
        name: "Flying Fish M",
        description:"skimboard",
        tag: 'boards-flying fish Medium medium',
        brand:"",
        image:'<img src="shop-images/boards/board-10.png" alt="board-img">',
        price: 2300,
        inCart: 0
    },
    {
        name: "Classic Shape Carbon ML",
        description:"skimboard",
        tag: 'boards-classic shape carbon medium-large Medium-Large',
        brand:"",
        image:'<img src="shop-images/boards/board-11.png" alt="board-img">',
        price: 2500,
        inCart: 0
    },
    {
        name: "Flying Fish L",
        description:"skimboard",
        tag: 'boards-flying fish Large large',
        brand:"",
        image:'<img src="shop-images/boards/board-12.png" alt="board-img">',
        price: 2600,
        inCart: 0
    },
//---------------------BAGS------------------//
    {
        name: "Delux Skimboard Travel Bag - Black",
        description:"Delux Skimboard Travel Bag - black",
        tag: 'delux-black bag bags ',
        brand:"",
        image:'<img src="shop-images/bags/bag1.png" alt="bag-img">',
        price: 900,
        inCart: 0
    },
    {
        name: "Delux Skimboard Travel Bag - Blue",
        description:"Delux Skimboard Travel Bag - blue",
        tag: 'delux-blue bag bags ',
        brand:"",
        image:'<img src="shop-images/bags/bag2.png" alt="bag-img">',
        price: 900,
        inCart: 0
    },
    {
        name: "Standard Skimboard Travel Bag - Pink",
        description:"Standard Skimboard Travel Bag - pink",
        tag: 'standard-pink bag bags ',
        brand:"",
        image:'<img src="shop-images/bags/bag3.png" alt="bag-img">',
        price: 650,
        inCart: 0
    },
    {
        name: "Standard Skimboard Travel Bag - Lime-green",
        description:"Standard Skimboard Travel Bag - lime-green",
        tag: 'standard-black bag bags ',
        brand:"",
        image:'<img src="shop-images/bags/bag4.png" alt="bag-img">',
        price: 650,
        inCart: 0
    }, 
    {
        name: "Standard Skimboard Travel Bag - red",
        description:"Standard Skimboard Travel Bag - red",
        tag: 'standard-red bag bags ',
        brand:"",
        image:'<img src="shop-images/bags/bag5.png" alt="bag-img">',
        price: 650,
        inCart: 0
    },  
// ----------WETSUITS-------------------//
    {
        name: "Reef blue",
        description:"Navy blue edition front zip 4mm long sleeve",
        tag:"wetsuit-Reef blue wetsuits",
        brand:"Reef reef",
        image:'<img src="shop-images/suits/suit2.png" alt="bag-img">',
        price: 2999,
        inCart:0,
       },
   {
    name: "Black Carbon",
    description:"Shadow black edition front zip 4.3mm long sleeve -ltd edition",
    tag:"wetsuit-Black Carbon wetsuits",
    brand:"quicksilver Quicksilver",
    image:'<img src="shop-images/suits/suit3.png" alt="bag-img">',
    price: 3200,
    inCart:0,
   },
   {
    name: "Silver Lining",
    description:"Silver stitch edition front zip 4.3mm long sleeve",
    tag:"wetsuit-Silver Lining wetsuits",
    brand:"Reef reef",
    image:'<img src="shop-images/suits/suit4.png" alt="bag-img">',
    price: 3000,
    inCart:0,
   },
   {
    name: "Chesty",
    description:"Black front zip 4.3mm long sleeve",
    tag:"Wetsuit Chesty wetsuits",
    brand:"Billabong billabong",
    image:'<img src="shop-images/suits/suit5.png" alt="bag-img">',
    price: 2600,
    inCart:0,
   },
   {
    name: "Shorty",
    description:"Black front zip 3mm short sleeve",
    tag:"Wetsuit Shorty wetsuits",
    brand:"Reef reef",
    image:'<img src="shop-images/suits/suit7.png" alt="bag-img">',
    price: 2000,
    inCart:0,
   },
   {
    name: "Shorty Chest",
    description:"Black front zip 3mm short sleeve",
    tag:"Wetsuit shorty chest wetsuits",
    brand:"Reef reef",
    image:'<img src="shop-images/suits/suit6.png" alt="bag-img">',
    price: 2100,
    inCart:0,
   },
   {
    name: "Light Blue",
    description:"Light blue front zip 4.3mm long sleeve - ladies",
    tag:"wetsuit wetsuits",
    brand:"Reef reef",
    image:'<img src="shop-images/suits/suit1.png" alt="bag-img">',
    price: 2900,
    inCart:0,
   },
   {
    name: "Dark Blue",
    description:"Dark blue front zip 4.3mm long sleeve - ladies",
    tag:"Wetsuit wetsuits",
    brand:"Reef reef",
    image:'<img src="shop-images/suits/suitL2.png" alt="bag-img">',
    price: 2800,
    inCart:0,
   }, 
   {
    name: "Full diver suit",
    description:"Black front zip 5mm short sleeve",
    tag:"Wetsuit wetsuits",
    brand:"Reef reef",
    image:'<img src="shop-images/suits/suitL1.png" alt="bag-img">',
    price: 4200,
    inCart:0,
   },
// ----------ACCESSORIES-------------------//
    {
    name: "Mr. Zogs - Sex Wax Quick Humps (Cold - Cool Purple)",
    description:" Mr. Zogs - Sex Wax Quick Humps (Cold - Cool Purple) wax-CC",
    tag:"wax-CC accessories",
    brand:"Mr.Zogs, mr",
    image:'<img src="shop-images/accessories/wax1.png" alt="bag-img">',
    price: 50,
    inCart:0,
    },
   {
    name: "Mr. Zogs - Sex Wax Quick Humps (Cold - Mid Warm Green)",
    description:" Mr. Zogs - Sex Wax Quick Humps (Cold - Mid Warm Green) wax-CM",
    tag:"wax-CM accessories",
    brand:"Mr.Zogs, mr",
    image:'<img src="shop-images/accessories/wax2.png" alt="bag-img">',
    price: 50,
    inCart:0,
   },
   {
    name: "Mr. Zogs - Sex Wax Quick Humps (Mid Cool - Warm Orange)",
    description:" Mr. Zogs - Sex Wax Quick Humps (Mid Cool - Warm Orange) ",
    tag:"wax-MW accessories",
    brand:"Mr.Zogs, mr",
    image:'<img src="shop-images/accessories/wax3.png" alt="bag-img">',
    price: 50,
    inCart:0,
   },
   {
    name: "Mr. Zogs - Sex Wax Quick Humps (Warm - Mild Tropic Red)",
    description:" Mr. Zogs - Sex Wax Quick Humps (Warm - Mild Tropic Red) ",
    tag:"wax-WM accessories",
    brand:"Mr.Zogs, mr",
    image:'<img src="shop-images/accessories/wax4.png" alt="bag-img">',
    price: 50,
    inCart:0,
   },
   {
    name: "Mrs. Palmers - 70g",
    description:"Mrs. Palmers - 70g ",
    tag:"wax-70G accessories",
    brand:"Mr.Zogs, mr",
    image:'<img src="shop-images/accessories/wax5.png" alt="bag-img">',
    price: 50,
    inCart:0,
   },
   {
    name: "Mrs. Palmers - 70g Comp",
    description:"Mrs. Palmers - 70g Comp ",
    tag:"wax-70Gcomp accessories",
    brand:"Mrs.Palmers, mrs",
    image:'<img src="shop-images/accessories/wax6.png" alt="bag-img">',
    price: 50,
    inCart:0,
   },
   {
    name: "Reef Traction pad",
    description:"Reef Traction pad - 3 piece traction pad (blue and grey)",
    tag:"traction pad(blue and grey) accessories",
    brand:"Reef reef",
    image:'<img src="shop-images/accessories/traction1.png" alt="bag-img">',
    price: 380,
    inCart:0,
   },
   {
    name: "Reef Traction pad (black)",
    description:"Reef Traction pad - 3 piece traction pad (black)",
    tag:"traction pad(black) accessories",
    brand:"Reef reef",
    image:'<img src="shop-images/accessories/traction2.png" alt="bag-img">',
    price: 350,
    inCart:0,
   }, 
   {
    name: "Reef Traction pad (black and grey)",
    description:"Reef Traction pad",
    tag:"traction pad(black and grey) accessories",
    brand:"Reef reef",
    image:'<img src="shop-images/accessories/traction3.png" alt="bag-img">',
    price: 380,
    inCart:0,
   },
   {
    name: "Portable Shower",
    description:"Portable Shower 20 litre portable shower",
    tag:"20 litre portable shower accessories",
    image:'<img src="shop-images/accessories/accessory1.png" alt="bag-img">',
    brand:"Reef reef",
    price: 150,
    inCart:0,
   },
   {
    name: " Reef Changing Mat",
    description:"Reef Changing Mat ",
    tag:"reef changing mat accessories",
    brand:"Reef reef",
    image:'<img src="shop-images/accessories/accessory2.png" alt="bag-img">',
    price: 350,
    inCart:0,
   },
   {
    name: "Ding Repair Kit",
    description:"Ding Repair Kit Epoxy Repair Kit (1 oz.)",
    tag:"Epoxy Repair Kit (1 oz.) accessories",
    brand:"Reef reef suncure Sun",
    image:'<img src="shop-images/accessories/ding-kit1.png" alt="bag-img">',
    price: 200,
    inCart:0,
   },
   {
    name: "SunCure ding repair kit",
    description:" SunCure ding repair kit Epoxy fiberfill (1 oz.)",
    tag:"Epoxy fiberfill (1 oz.) accessories",
    brand:"suncure Sun",
    image:'<img src="shop-images/accessories/ding-kit2.png" alt="bag-img">',
    price: 150,
    inCart:0,
   },
   {
    name: "SunCure ding repair kit",
    description:"SunCure ding repair kit polyester fiberfill (1 oz.)",
    tag:"polyester fiberfill (1 oz.) accessories",
    brand:"suncure Sun",
    image:'<img src="shop-images/accessories/ding-kit3.png" alt="bag-img" >',
    price: 130,
    inCart:0,
   },
// --------------------APARREL---------------------//
    {
    name: "",
    description:"",
    tag:"",
    brand:"",
    image:'',
    price: "",
    inCart:0,
   },
    {
    name: "",
    description:"",
    tag:"",
    brand:"",
    image:'',
    price: "",
    inCart:0,
   },
    {
    name: "",
    description:"",
    tag:"",
    brand:"",
    image:'',
    price: "",
    inCart:0,
   },
    {
    name: "",
    description:"",
    tag:"",
    brand:"",
    image:'',
    price: "",
    inCart:0,
   },
    {
    name: "",
    description:"",
    tag:"",
    brand:"",
    image:'',
    price: "",
    inCart:0,
   },
    {
    name: "",
    description:"",
    tag:"",
    brand:"",
    image:'',
    price: "",
    inCart:0,
   },
    {
    name: "",
    description:"",
    tag:"",
    brand:"",
    image:'',
    price: "",
    inCart:0,
   },
]